version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/backend/  # ✅ 백엔드 전용 폴더로 변경

hooks:
  ApplicationStop:
    - location: backend/scripts/stop_container.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: backend/scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: backend/scripts/set_env.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: backend/scripts/start_container.sh
      timeout: 300
      runas: ubuntu

